services:
  mongo:
    image: mongo:7
    container_name: indiamart-scraper-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: indiamart_scraper
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: indiamart-scraper-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
